Import lxc_4.0.12.orig.tar.gz

diff --git a/src/tests/lxc-test-unpriv b/src/tests/lxc-test-unpriv
--- a/src/tests/lxc-test-unpriv
+++ b/src/tests/lxc-test-unpriv
@@ -42,7 +42,7 @@ if modprobe -q overlayfs; then
         mkdir ${MOUNTDIR}/{lowerdir,upperdir,workdir,overlayfs}
         mount -t overlayfs -o lowerdir="${MOUNTDIR}/lowerdir",upperdir="${MOUNTDIR}/upperdir",workdir="${MOUNTDIR}/workdir" none "${MOUNTDIR}/overlayfs"
 
-        CORRECT_LINK_TARGET="${MOUNTDIR}/overlayfs/dummy_file"
+        CORRECT_LINK_TARGET="${MOUNTDIR}/overlayfs/placeholder_file"
         exec 9> "${CORRECT_LINK_TARGET}"
 
         DETECTED_LINK_TARGET=$(readlink -q /proc/$$/fd/9)
@@ -62,15 +62,20 @@ if modprobe -q overlayfs; then
         fi
 fi
 
-which newuidmap >/dev/null 2>&1 || { echo "'newuidmap' command is missing" >&2; exit 1; }
+command -v newuidmap >/dev/null 2>&1 || { echo "'newuidmap' command is missing" >&2; exit 1; }
 
 DONE=0
-KNOWN_RELEASES="precise trusty xenial yakkety zesty"
+UNPRIV_LOG=$(mktemp --dry-run)
 cleanup() {
 	cd /
 
-	run_cmd lxc-stop -n c2 -k || true
-	run_cmd lxc-stop -n c1 -k || true
+	if [ $DONE -eq 0 ]; then
+		cat "${UNPRIV_LOG}"
+	fi
+	rm -f "${UNPRIV_LOG}" || true
+
+	run_cmd lxc-stop -n c2 -k -l trace -o "${UNPRIV_LOG}" || true
+	run_cmd lxc-stop -n c1 -k -l trace -o "${UNPRIV_LOG}" || true
 	pkill -u $(id -u $TUSER) -9 || true
 
 	sed -i '/lxcunpriv/d' /run/lxc/nics /etc/lxc/lxc-usernet
@@ -84,23 +89,20 @@ cleanup() {
 		echo "FAIL"
 		exit 1
 	fi
+
 	echo "PASS"
 }
 
 run_cmd() {
 	sudo -i -u $TUSER \
 	    env http_proxy=${http_proxy:-} https_proxy=${https_proxy:-} \
-	        XDG_RUNTIME_DIR=/run/user/$(id -u $TUSER) $*
+	        XDG_RUNTIME_DIR=/run/user/$(id -u $TUSER) ASAN_OPTIONS=${ASAN_OPTIONS:-} \
+		UBSAN_OPTIONS=${UBSAN_OPTIONS:-} $*
 }
 
 # create a test user
 TUSER=lxcunpriv
 HDIR=/home/$TUSER
-
-ARCH=i386
-if type dpkg >/dev/null 2>&1; then
-	ARCH=$(dpkg --print-architecture)
-fi
 
 trap cleanup EXIT SIGHUP SIGINT SIGTERM
 set -eu
@@ -128,7 +130,7 @@ chown -R $TUSER: /run/user/$(id -u $TUSER)
 
 cd $HDIR
 
-if which cgm >/dev/null 2>&1; then
+if command -v cgm >/dev/null 2>&1; then
 	cgm create all $TUSER
 	cgm chown all $TUSER $(id -u $TUSER) $(id -g $TUSER)
 	cgm movepid all $TUSER $$
@@ -156,62 +158,45 @@ else
 	done
 fi
 
-# default release is trusty, or the systems release if recognized
-release=trusty
-if [ -f /etc/lsb-release ]; then
-    . /etc/lsb-release
-    rels=$(ubuntu-distro-info --supported 2>/dev/null) ||
-        rels="$KNOWN_RELEASES"
-    for r in $rels; do
-        [ "$DISTRIB_CODENAME" = "$r" ] && release="$r"
-    done
-fi
-
-# Copy the download template cache if available
-run_cmd mkdir -p $HDIR/.cache/lxc
-[ -d /var/cache/lxc/download ] && \
-    cp -R /var/cache/lxc/download $HDIR/.cache/lxc && \
-    chown -R $TUSER: $HDIR/.cache/lxc
-
-run_cmd lxc-create -t download -n c1 -- -d ubuntu -r $release -a $ARCH
+run_cmd lxc-create -t busybox -n c1 -l trace -o "${UNPRIV_LOG}"
 
 # Make sure we can start it - twice
 
-for count in `seq 1 2`; do
-    run_cmd lxc-start -n c1 -d
+for count in $(seq 1 2); do
+    run_cmd lxc-start -n c1 -d -l trace -o "${UNPRIV_LOG}"
 
-    p1=$(run_cmd lxc-info -n c1 -p -H)
+    p1=$(run_cmd lxc-info -n c1 -p -H -l trace -o "${UNPRIV_LOG}")
     [ "$p1" != "-1" ] || { echo "Failed to start container c1 (run $count)"; false; }
 
-    run_cmd lxc-info -n c1
-    run_cmd lxc-attach -n c1 -- /bin/true
+    run_cmd lxc-info -n c1 -l trace -o "${UNPRIV_LOG}"
+    run_cmd lxc-attach -n c1 -l trace -o "${UNPRIV_LOG}" -- /bin/true
 
-    run_cmd lxc-stop -n c1 -k
+    run_cmd lxc-stop -n c1 -k -l trace -o "${UNPRIV_LOG}"
 done
 
-run_cmd lxc-copy -s -n c1 -N c2
-run_cmd lxc-start -n c2 -d
-p1=$(run_cmd lxc-info -n c2 -p -H)
+run_cmd lxc-copy -s -n c1 -N c2 -l trace -o "${UNPRIV_LOG}"
+run_cmd lxc-start -n c2 -d -l trace -o "${UNPRIV_LOG}"
+p1=$(run_cmd lxc-info -n c2 -p -H -l trace -o "${UNPRIV_LOG}")
 [ "$p1" != "-1" ] || { echo "Failed to start container c2"; false; }
 
-run_cmd lxc-stop -n c2 -k
+run_cmd lxc-stop -n c2 -k -l trace -o "${UNPRIV_LOG}"
 
-if which cgm >/dev/null 2>&1; then
+if command -v cgm >/dev/null 2>&1; then
     echo "Testing containers under different cgroups per subsystem"
     run_cmd cgm create freezer x1/x2
     cgm movepid freezer x1 $$
-    run_cmd lxc-start -n c1 -d
-    p1=$(run_cmd lxc-info -n c1 -p -H)
+    run_cmd lxc-start -n c1 -d -l trace -o "${UNPRIV_LOG}"
+    p1=$(run_cmd lxc-info -n c1 -p -H -l trace -o "${UNPRIV_LOG}")
     [ "$p1" != "-1" ] || { echo "Failed to start container c1"; false; }
-    run_cmd lxc-info -n c1
-    run_cmd lxc-attach -n c1 -- /bin/true
-    run_cmd lxc-cgroup -n c1 freezer.state
+    run_cmd lxc-info -n c1 -l trace -o "${UNPRIV_LOG}"
+    run_cmd lxc-attach -n c1 -l trace -o "${UNPRIV_LOG}" -- /bin/true
+    run_cmd lxc-cgroup -n c1 freezer.state -l trace -o "${UNPRIV_LOG}"
 
     echo "Testing lxc-attach and lxc-cgroup from different cgroup"
     cgm movepid freezer x2 $$
-    run_cmd lxc-attach -n c1 -- /bin/true
-    run_cmd lxc-cgroup -n c1 freezer.state
-    run_cmd lxc-cgroup -n c1 memory.limit_in_bytes
+    run_cmd lxc-attach -n c1 -l trace -o "${UNPRIV_LOG}" -- /bin/true
+    run_cmd lxc-cgroup -n c1 -l trace -o "${UNPRIV_LOG}" freezer.state
+    run_cmd lxc-cgroup -n c1 -l trace -o "${UNPRIV_LOG}" memory.limit_in_bytes
 fi
 
 DONE=1
