Import lxc_1.0.6.orig.tar.gz

diff --git a/src/tests/lxc-test-unpriv b/src/tests/lxc-test-unpriv
--- a/src/tests/lxc-test-unpriv
+++ b/src/tests/lxc-test-unpriv
@@ -33,7 +33,8 @@ DONE=0
 cleanup() {
 	cd /
 
-	run_cmd lxc-stop -n c1 -k
+	run_cmd lxc-stop -n c2 -k || true
+	run_cmd lxc-stop -n c1 -k || true
 	pkill -u $(id -u $TUSER) -9
 
 	sed -i '/lxcunpriv/d' /run/lxc/nics /etc/lxc/lxc-usernet
@@ -84,14 +85,18 @@ lxc.network.link = lxcbr0
 lxc.id_map = u 0 910000 9999
 lxc.id_map = g 0 910000 9999
 EOF
-chown -R $TUSER $HDIR
+chown -R $TUSER: $HDIR
 
 mkdir -p /run/user/$(id -u $TUSER)
-chown -R $TUSER /run/user/$(id -u $TUSER)
+chown -R $TUSER: /run/user/$(id -u $TUSER)
 
 cd $HDIR
 
-if [ -e /sys/fs/cgroup/cgmanager/sock ]; then
+if which cgm >/dev/null 2>&1; then
+	cgm create all $TUSER
+	cgm chown all $TUSER $(id -u $TUSER) $(id -g $TUSER)
+	cgm movepid all $TUSER $$
+elif [ -e /sys/fs/cgroup/cgmanager/sock ]; then
 	for d in $(cut -d : -f 2 /proc/self/cgroup); do
 		dbus-send --print-reply --address=unix:path=/sys/fs/cgroup/cgmanager/sock \
 			--type=method_call /org/linuxcontainers/cgmanager org.linuxcontainers.cgmanager0_0.Create \
@@ -108,10 +113,16 @@ if [ -e /sys/fs/cgroup/cgmanager/sock ]; then
 else
 	for d in /sys/fs/cgroup/*; do
 		[ ! -d $d/lxctest ] && mkdir $d/lxctest
-		chown -R $TUSER $d/lxctest
+		chown -R $TUSER: $d/lxctest
 		echo $$ > $d/lxctest/tasks
 	done
 fi
+
+# Copy the download template cache if available
+run_cmd mkdir -p $HDIR/.cache/lxc
+[ -d /var/cache/lxc/download ] && \
+    cp -R /var/cache/lxc/download $HDIR/.cache/lxc && \
+    chown -R $TUSER: $HDIR/.cache/lxc
 
 run_cmd lxc-create -t download -n c1 -- -d ubuntu -r trusty -a $ARCH
 run_cmd lxc-start -n c1 -d
@@ -121,5 +132,13 @@ p1=$(run_cmd lxc-info -n c1 -p -H)
 
 run_cmd lxc-info -n c1
 run_cmd lxc-attach -n c1 -- /bin/true
+
+run_cmd lxc-stop -n c1
+run_cmd lxc-clone -s -o c1 -n c2
+run_cmd lxc-start -n c2 -d
+p1=$(run_cmd lxc-info -n c2 -p -H)
+[ "$p1" != "-1" ] || { echo "Failed to start container c2"; false; }
+
+run_cmd lxc-stop -n c2
 
 DONE=1
