Import lxc_2.1.0.orig.tar.gz

diff --git a/templates/lxc-debian.in b/templates/lxc-debian.in
--- a/templates/lxc-debian.in
+++ b/templates/lxc-debian.in
@@ -34,12 +34,35 @@ done
 export PATH=$PATH:/usr/sbin:/usr/bin:/sbin:/bin
 export GREP_OPTIONS=""
 
-MIRROR=${MIRROR:-http://httpredir.debian.org/debian}
+MIRROR=${MIRROR:-http://deb.debian.org/debian}
 SECURITY_MIRROR=${SECURITY_MIRROR:-http://security.debian.org/}
 LOCALSTATEDIR="@LOCALSTATEDIR@"
 LXC_TEMPLATE_CONFIG="@LXCTEMPLATECONFIG@"
 # Allows the lxc-cache directory to be set by environment variable
 LXC_CACHE_PATH=${LXC_CACHE_PATH:-"$LOCALSTATEDIR/cache/lxc"}
+
+find_interpreter()
+{
+    given_interpreter=$(basename "$1")
+
+    if [ ! -d /proc/sys/fs/binfmt_misc/ ] ; then
+        return 1
+    fi
+    for file in /proc/sys/fs/binfmt_misc/* ; do
+        if [ "$file" = "/proc/sys/fs/binfmt_misc/register" -o \
+             "$file" = "/proc/sys/fs/binfmt_misc/status" ] ; then
+            continue
+        fi
+        interpreter_path=$(sed -n "/^interpreter/s/interpreter \([^[:space:]]*\)/\1/p" "$file")
+        interpreter=$(basename "$interpreter_path")
+
+        if [ "$given_interpreter" = "$interpreter" ] ; then
+            echo "$interpreter_path"
+            return 0
+        fi
+    done
+    return 1
+}
 
 configure_debian()
 {
@@ -158,6 +181,14 @@ EOF
         echo "Timezone in container is not configured. Adjust it manually."
     fi
 
+    if [ -n "$authkey" ]; then
+        local ssh_dir_path="${rootfs}/root/.ssh"
+        mkdir -p "$ssh_dir_path"
+        cp "$authkey" "${ssh_dir_path}/authorized_keys"
+        chmod 700 "$ssh_dir_path"
+        echo "Inserted SSH public key from '$authkey' into /root/.ssh/authorized_keys"
+    fi
+
     return 0
 }
 
@@ -234,7 +265,7 @@ configure_debian_systemd()
     chroot "${rootfs}" ln -s /dev/null /etc/systemd/system/systemd-udevd.service
     chroot "${rootfs}" ln -s /lib/systemd/system/multi-user.target /etc/systemd/system/default.target
     # Setup getty service on the ttys we are going to allow in the
-    # default config.  Number should match lxc.tty
+    # default config.  Number should match lxc.tty.max
     ( cd "${rootfs}/etc/systemd/system/getty.target.wants"
         for i in $(seq 1 "$num_tty") ; do ln -sf ../getty\@.service getty@tty"${i}".service; done )
 
@@ -247,10 +278,45 @@ configure_debian_systemd()
     return 0
 }
 
+# Check if given path is in a btrfs partition
+is_btrfs()
+{
+    [ -e "$1" -a "$(stat -f -c '%T' "$1")" = "btrfs" ]
+}
+
+# Check if given path is the root of a btrfs subvolume
+is_btrfs_subvolume()
+{
+    [ -d "$1" -a "$(stat -f -c '%T' "$1")" = "btrfs" -a "$(stat -c '%i' "$1")" -eq 256 ]
+}
+
+try_mksubvolume()
+{
+    path=$1
+    [ -d "$path" ] && return 0
+    mkdir -p "$(dirname "$path")"
+    if which btrfs >/dev/null 2>&1 && is_btrfs "$(dirname "$path")"; then
+        btrfs subvolume create "$path"
+    else
+        mkdir -p "$path"
+    fi
+}
+
+try_rmsubvolume()
+{
+    path=$1
+    [ -d "$path" ] || return 0
+    if which btrfs >/dev/null 2>&1 && is_btrfs_subvolume "$path"; then
+        btrfs subvolume delete "$path"
+    else
+        rm -rf "$path"
+    fi
+}
+
 cleanup()
 {
-    rm -rf "$cache/partial-$release-$arch"
-    rm -rf "$cache/rootfs-$release-$arch"
+    try_rmsubvolume "$cache/partial-$release-$arch"
+    try_rmsubvolume "$cache/rootfs-$release-$arch"
 }
 
 download_debian()
@@ -277,6 +343,8 @@ openssh-server
     cache=$1
     arch=$2
     release=$3
+    interpreter="$4"
+    interpreter_path="$5"
 
     trap cleanup EXIT SIGHUP SIGINT SIGTERM
 
@@ -299,7 +367,7 @@ openssh-server
             | gpg --import --no-default-keyring --keyring="${releasekeyring}"
     fi
     # check the mini debian was not already downloaded
-    mkdir -p "$cache/partial-$release-$arch"
+    try_mksubvolume "$cache/partial-$release-$arch"
     if [ $? -ne 0 ]; then
         echo "Failed to create '$cache/partial-$release-$arch' directory"
         return 1
@@ -307,12 +375,33 @@ openssh-server
 
     # download a mini debian into a cache
     echo "Downloading debian minimal ..."
-    debootstrap --verbose --variant=minbase --arch="$arch" \
-        --include="$packages" --keyring="${releasekeyring}" \
-        "$release" "$cache/partial-$release-$arch" "$MIRROR"
-    if [ $? -ne 0 ]; then
-        echo "Failed to download the rootfs, aborting."
-        return 1
+    if [ "$interpreter" = "" ] ; then
+        debootstrap --verbose --variant=minbase --arch="$arch" \
+            --include=$packages --keyring="${releasekeyring}" \
+            "$release" "$cache/partial-$release-$arch" "$MIRROR"
+        if [ $? -ne 0 ]; then
+            echo "Failed to download the rootfs, aborting."
+            return 1
+        fi
+    else
+        debootstrap --foreign --verbose --variant=minbase --arch="$arch" \
+            --include=$packages --keyring="${releasekeyring}" \
+            "$release" "$cache/partial-$release-$arch" "$MIRROR"
+        if [ $? -ne 0 ]; then
+            echo "Failed to download the rootfs, aborting."
+            return 1
+        fi
+        mkdir -p "$(basename "$cache/partial-$release-$arch/$interpreter_path")"
+        cp "$interpreter" "$cache/partial-$release-$arch/$interpreter_path"
+        if [ $? -ne 0 ]; then
+            echo "failed to copy $interpreter to $cache/partial-$release-$arch/$interpreter_path"
+            return 1
+        fi
+        chroot "$cache/partial-$release-$arch" debootstrap/debootstrap --second-stage
+        if [ $? -ne 0 ]; then
+            echo "failed to update the rootfs, aborting"
+            return 1
+        fi
     fi
 
     mv "$1/partial-$release-$arch" "$1/rootfs-$release-$arch"
@@ -334,8 +423,18 @@ copy_debian()
 
     # make a local copy of the minidebian
     echo -n "Copying rootfs to $rootfs..."
-    mkdir -p "$rootfs"
-    rsync -Ha "$cache/rootfs-$release-$arch"/ "$rootfs"/ || return 1
+    try_mksubvolume "$rootfs"
+    if which btrfs >/dev/null 2>&1 && \
+       is_btrfs_subvolume "$cache/rootfs-$release-$arch" && \
+       is_btrfs_subvolume "$rootfs"; then
+      realrootfs="$(dirname "$config")"/rootfs
+      [ "$rootfs" = "$realrootfs" ] || umount "$rootfs" || return 1
+      btrfs subvolume delete "$realrootfs" || return 1
+      btrfs subvolume snapshot "$cache/rootfs-$release-$arch" "$realrootfs" || return 1
+      [ "$rootfs" = "$realrootfs" ] || mount --bind "$realrootfs" "$rootfs" || return 1
+    else
+        rsync -SHaAX "$cache/rootfs-$release-$arch"/ $rootfs/ || return 1
+    fi
     return 0
 }
 
@@ -345,6 +444,9 @@ install_debian()
     release=$2
     arch=$3
     cache="$4/debian"
+    interpreter="$5"
+    interpreter_path="$6"
+    flushcache=$7
     mkdir -p $LOCALSTATEDIR/lock/subsys/
     (
         flock -x 9
@@ -353,9 +455,14 @@ install_debian()
             return 1
         fi
 
+        if [ "$flushcache" -eq 1 ]; then
+            echo "Flushing cache..."
+            cleanup
+        fi
+
         echo "Checking cache download in $cache/rootfs-$release-$arch ... "
         if [ ! -e "$cache/rootfs-$release-$arch" ]; then
-            download_debian "$cache" "$arch" "$release"
+            download_debian "$cache" "$arch" "$release" "$interpreter" "$interpreter_path"
             if [ $? -ne 0 ]; then
                 echo "Failed to download 'debian base'"
                 return 1
@@ -386,9 +493,9 @@ copy_configuration()
     # Generate the configuration file
     # if there is exactly one veth network entry, make sure it has an
     # associated hwaddr.
-    nics=$(grep -ce '^lxc\.network\.type[ \t]*=[ \t]*veth' "$path/config")
+    nics=$(grep -ce '^lxc\.net\.0\.type[ \t]*=[ \t]*veth' "$path/config")
     if [ "$nics" -eq 1 ]; then
-        grep -q "^lxc.network.hwaddr" "$path/config" || sed -i -e "/^lxc\.network\.type[ \t]*=[ \t]*veth/a lxc.network.hwaddr = 00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//')" "$path/config"
+        grep -q "^lxc.net.0.hwaddr" "$path/config" || sed -i -e "/^lxc\.net\.0\.type[ \t]*=[ \t]*veth/a lxc.net.0.hwaddr = 00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//')" "$path/config"
     fi
 
     ## Add all the includes
@@ -404,12 +511,13 @@ copy_configuration()
     ## Add the container-specific config
     echo "" >> "$path/config"
     echo "# Container specific configuration" >> "$path/config"
-    grep -q "^lxc.rootfs" "$path/config" 2> /dev/null || echo "lxc.rootfs = $rootfs" >> "$path/config"
+    grep -q "^lxc.rootfs.path" "$path/config" 2> /dev/null || echo "lxc.rootfs.path = $rootfs" >> "$path/config"
 
     cat <<EOF >> $path/config
-lxc.tty = $num_tty
-lxc.utsname = $hostname
+lxc.tty.max = $num_tty
+lxc.uts.name = $hostname
 lxc.arch = $arch
+lxc.pty.max = 1024
 EOF
 
     if [ $? -ne 0 ]; then
@@ -426,6 +534,7 @@ post_process()
     local release="$1"; shift
     local arch="$1"; shift
     local hostarch="$1"; shift
+    local interpreter="$1"; shift
     local packages="$*"
 
     # Disable service startup
@@ -436,7 +545,7 @@ EOF
     chmod +x "${rootfs}/usr/sbin/policy-rc.d"
 
     # If the container isn't running a native architecture, setup multiarch
-    if [ "${arch}" != "${hostarch}" ]; then
+    if [ "$interpreter" = "" -a "${arch}" != "${hostarch}" ]; then
         # Test if dpkg supports multiarch
         if ! chroot "$rootfs" dpkg --print-foreign-architectures 2>&1; then
             chroot "$rootfs" dpkg --add-architecture "${hostarch}"
@@ -445,7 +554,7 @@ EOF
 
     # Write a new sources.list containing both native and multiarch entries
     > "${rootfs}/etc/apt/sources.list"
-    if [ "${arch}" = "${hostarch}" ]; then
+    if [ "$interpreter" != "" -a "${arch}" = "${hostarch}" ]; then
         write_sourceslist "${rootfs}" "${release}" "${arch}"
     else
         write_sourceslist "${rootfs}" "${release}"
@@ -461,6 +570,7 @@ EOF
 
     # Re-enable service startup
     rm "${rootfs}/usr/sbin/policy-rc.d"
+    
     # end
 }
 
@@ -497,14 +607,17 @@ Template specific options can be passed to lxc-create after a '--' like this:
 Usage: $1 -h|--help -p|--path=<path> [-c|--clean] [-a|--arch=<arch>] [-r|--release=<release>]
                                      [--mirror=<mirror>] [--security-mirror=<security mirror>]
                                      [--package=<package_name1,package_name2,...>]
+                                     [-I|--interpreter-path=<interpreter path>]
+                                     [-F | --flush-cache] [-S|--auth-key=<keyfile>]
 
 Options :
 
   -h, --help             print this help text
   -p, --path=PATH        directory where config and rootfs of this VM will be kept
+  -S, --auth-key=KEYFILE SSH public key to inject into the container as the root user.
   -a, --arch=ARCH        The container architecture. Can be one of: i686, x86_64,
                          amd64, armhf, armel, powerpc. Defaults to host arch.
-  -r, --release=RELEASE  Debian release. Can be one of: wheezy, jessie, stretch, sid.
+  -r, --release=RELEASE  Debian release. Can be one of: wheezy, jessie, stretch, buster, sid.
                          Defaults to current stable.
   --mirror=MIRROR        Debian mirror to use during installation. Overrides the MIRROR
                          environment variable (see below).
@@ -515,6 +628,9 @@ Options :
                          List of additional packages to install. Comma separated, without space.
   -c, --clean            only clean up the cache and terminate
   --enable-non-free      include also Debian's contrib and non-free repositories.
+  -I|--interpreter-path=INTERPRETER-PATH
+                         Path of the binfmt interpreter to copy to the rootfs
+  -F | --flush-cache     Flush the debian release cache
 
 Environment variables:
 
@@ -527,7 +643,7 @@ EOF
     return 0
 }
 
-options=$(getopt -o hp:n:a:r:c -l arch:,clean,help,enable-non-free,mirror:,name:,packages:,path:,release:,rootfs:,security-mirror: -- "$@")
+options=$(getopt -o hp:n:a:r:cI:FS: -l arch:,auth-key:,clean,help,enable-non-free,mirror:,name:,packages:,path:,release:,rootfs:,security-mirror:,interpreter-path:,flush-cache -- "$@")
 if [ $? -ne 0 ]; then
         usage "$(basename "$0")"
         exit 1
@@ -543,6 +659,8 @@ elif [ "$arch" = "x86_64" ]; then
     arch="amd64"
 elif [ "$arch" = "armv7l" ]; then
     arch="armhf"
+elif [ "$arch" = "aarch64" ]; then
+    arch="arm64"
 elif [ "$arch" = "ppc" ]; then
     arch="powerpc"
 elif [ "$arch" = "ppc64le" ]; then
@@ -554,6 +672,7 @@ elif [ "$arch" = "mips64" -a "$littleendian" = "yes" ]; then
 fi
 hostarch=$arch
 mainonly=1
+flushcache=0
 
 while true
 do
@@ -562,6 +681,9 @@ do
            --)                shift 1; break ;;
 
         -a|--arch)            arch=$2; shift 2;;
+        -S|--auth-key)        authkey=$2; shift 2;;
+        -I|--interpreter-path)
+                              interpreter="$2"; shift 2;;
         -c|--clean)           clean=1; shift 1;;
            --enable-non-free) mainonly=0; shift 1;;
            --mirror)          MIRROR=$2; shift 2;;
@@ -571,6 +693,7 @@ do
         -r|--release)         release=$2; shift 2;;
            --rootfs)          rootfs=$2; shift 2;;
            --security-mirror) SECURITY_MIRROR=$2; shift 2;;
+        -F|--flush-cache)     flushcache=1; shift 1;;
         *)                    break ;;
     esac
 done
@@ -588,20 +711,40 @@ if [ "$arch" = "x86_64" ]; then
     arch=amd64
 fi
 
-if [ $hostarch = "i386" -a $arch = "amd64" ]; then
-    echo "can't create $arch container on $hostarch"
-    exit 1
-fi
+if [ "$interpreter" = "" ] ; then
+    if [ $hostarch = "i386" -a $arch = "amd64" ]; then
+        echo "can't create $arch container on $hostarch"
+        exit 1
+    fi
 
-if [ $hostarch = "armhf" -o $hostarch = "armel" ] && \
-   [ $arch != "armhf" -a $arch != "armel" ]; then
-    echo "can't create $arch container on $hostarch"
-    exit 1
-fi
+    if [ $hostarch = "armhf" -o $hostarch = "armel" ] && \
+       [ $arch != "armhf" -a $arch != "armel" ]; then
+        echo "can't create $arch container on $hostarch"
+        exit 1
+    fi
 
-if [ $hostarch = "powerpc" -a $arch != "powerpc" ]; then
-    echo "can't create $arch container on $hostarch"
-    exit 1
+    if [ $hostarch = "powerpc" -a $arch != "powerpc" ]; then
+        echo "can't create $arch container on $hostarch"
+        exit 1
+    fi
+
+    if [ $hostarch = "mips" -a $arch != "mips" ] || \
+       [ $hostarch = "mipsel" -a $arch != "mipsel" ] || \
+       [ $hostarch = "mips64" -a $arch != "mips" -a $arch != "mips64" ] || \
+       [ $hostarch = "mips64el" -a $arch != "mipsel" -a $arch != "mips64el" ]; then
+        echo "can't create $arch container on $hostarch"
+        exit 1
+    fi
+else
+    if ! file -b "${interpreter}" |grep -q "statically linked" ; then
+        echo "'${interpreter}' must be statically linked" 1>&2
+        exit 1
+    fi
+    interpreter_path=$(find_interpreter "$interpreter")
+    if [ $? -ne 0 ] ; then
+        echo "no binfmt interpreter using $(basename "$interpreter")" 1>&2
+        exit 1
+    fi
 fi
 
 type debootstrap
@@ -620,9 +763,22 @@ if [ "$(id -u)" != "0" ]; then
     exit 1
 fi
 
+if [ -n "$authkey" ]; then
+    if [ ! -f "$authkey" ]; then
+	echo "SSH keyfile '$authkey' not found"
+	exit 1
+    fi
+    # This is mostly to prevent accidental uage of the private key instead
+    # of the public key.
+    if [ "${authkey: -4}" != ".pub" ]; then
+	echo "SSH keyfile '$authkey' does not end with '.pub'"
+	exit 1
+    fi
+fi
+
 current_release=$(wget "${MIRROR}/dists/stable/Release" -O - 2> /dev/null | head |awk '/^Codename: (.*)$/ { print $2; }')
 release=${release:-${current_release}}
-valid_releases=('wheezy' 'jessie' 'stretch' 'sid')
+valid_releases=('wheezy' 'jessie' 'stretch' 'buster' 'sid')
 if [[ ! "${valid_releases[*]}" =~ (^|[^[:alpha:]])$release([^[:alpha:]]|$) ]]; then
     echo "Invalid release ${release}, valid ones are: ${valid_releases[*]}"
     exit 1
@@ -631,21 +787,21 @@ fi
 # detect rootfs
 config="$path/config"
 if [ -z "$rootfs" ]; then
-    if grep -q '^lxc.rootfs' "$config" 2> /dev/null ; then
-        rootfs=$(awk -F= '/^lxc.rootfs[ \t]+=/{ print $2 }' "$config")
+    if grep -q '^lxc.rootfs.path' "$config" 2> /dev/null ; then
+        rootfs=$(awk -F= '/^lxc.rootfs.path[ \t]+=/{ print $2 }' "$config")
     else
         rootfs=$path/rootfs
     fi
 fi
 
 # determine the number of ttys - default is 4
-if grep -q '^lxc.tty' "$config" 2> /dev/null ; then
-    num_tty=$(awk -F= '/^lxc.tty[ \t]+=/{ print $2 }' "$config")
+if grep -q '^lxc.tty.max' "$config" 2> /dev/null ; then
+    num_tty=$(awk -F= '/^lxc.tty.max[ \t]+=/{ print $2 }' "$config")
 else
     num_tty=4
 fi
 
-install_debian "$rootfs" "$release" "$arch" "$LXC_CACHE_PATH"
+install_debian "$rootfs" "$release" "$arch" "$LXC_CACHE_PATH" "$interpreter" "$interpreter_path" "$flushcache"
 if [ $? -ne 0 ]; then
     echo "failed to install debian"
     exit 1
@@ -665,7 +821,7 @@ fi
 
 configure_debian_systemd "$path" "$rootfs" "$config" $num_tty
 
-post_process "${rootfs}" "${release}" "${arch}" "${hostarch}" "${packages}"
+post_process "${rootfs}" "${release}" ${arch} ${hostarch} "${interpreter}" "${packages}"
 
 if [ ! -z "$clean" ]; then
     clean || exit 1
