Import lxc_1.1.0.alpha1.orig.tar.gz

diff --git a/templates/lxc-oracle.in b/templates/lxc-oracle.in
--- a/templates/lxc-oracle.in
+++ b/templates/lxc-oracle.in
@@ -9,7 +9,7 @@
 # Modified for Oracle Linux 5
 # Wim Coekaerts <wim.coekaerts@oracle.com>
 #
-# Modified for Oracle Linux 6, combined OL4,5,6 into one template script
+# Modified for Oracle Linux 6,7 combined OL4,5,6 into one template script
 # Dwight Engen <dwight.engen@oracle.com>
 #
 # This library is free software; you can redistribute it and/or
@@ -84,7 +84,7 @@ container_rootfs_patch()
             mkdir -p $container_rootfs/usr/lib/yum-plugins
             cp @DATADIR@/lxc/lxc-patch.py $container_rootfs/usr/lib/yum-plugins
         fi
-        if [ $container_release_major = "6" ]; then
+        if [ $container_release_major -ge "6" ]; then
             mkdir -p $container_rootfs/usr/share/yum-plugins
             cp @DATADIR@/lxc/lxc-patch.py $container_rootfs/usr/share/yum-plugins
         fi
@@ -92,7 +92,7 @@ container_rootfs_patch()
         cat <<EOF > $container_rootfs/etc/yum/pluginconf.d/lxc-patch.conf
 [main]
 enabled=1
-packages=initscripts,iptables,selinux-policy,readahead,udev,util-linux-ng
+packages=dbus,initscripts,iptables,openssh-server,setup,selinux-policy,readahead,udev,util-linux,util-linux-ng
 EOF
     fi
 
@@ -140,6 +140,43 @@ EOF
     if [ -f $container_rootfs/usr/sbin/selinuxenabled ]; then
         mv $container_rootfs/usr/sbin/selinuxenabled $container_rootfs/usr/sbin/selinuxenabled.lxcorig
         ln -s /bin/false $container_rootfs/usr/sbin/selinuxenabled
+    fi
+
+    # ensure /dev/ptmx refers to the newinstance devpts of the container, or
+    # pty's will get crossed up with the hosts (https://lkml.org/lkml/2012/1/23/512)
+    rm -f $container_rootfs/dev/ptmx
+    ln -s pts/ptmx $container_rootfs/dev/ptmx
+
+    # OL7 has systemd, no rc.sysinit
+    if [ $container_release_major = "7" ]; then
+        # from mhw in the fedora template: We do need to disable the
+        # "ConditionalPathExists=/dev/tty0" line or no gettys are started on
+        # the ttys in the container. Lets do it in an override copy of the
+        # service so it can still pass rpm verifies and not be automatically
+        # updated by a new systemd version.
+        sed -e 's/^ConditionPathExists=/#LXC ConditionPathExists=/' \
+            < $container_rootfs/usr/lib/systemd/system/getty\@.service \
+            > $container_rootfs/etc/systemd/system/getty\@.service
+        # Setup getty service on the 4 ttys we are going to allow in the
+        # default config.  Number should match lxc.tty
+        ( cd $container_rootfs/etc/systemd/system/getty.target.wants
+            for i in 1 2 3 4 ; do ln -sf ../getty\@.service getty@tty${i}.service; done )
+        # We only want to spawn a getty on /dev/console in lxc, libvirt-lxc
+        # symlinks /dev/console to /dev/tty1
+        sed -i '/Before=getty.target/a ConditionVirtualization=lxc' $container_rootfs/usr/lib/systemd/system/console-getty.service
+
+        # disable some systemd services, set default boot, sigpwr target
+        rm -f $container_rootfs/usr/lib/systemd/system/sysinit.target.wants/kmod-static-nodes.service
+        chroot $container_rootfs systemctl -q disable graphical.target
+        chroot $container_rootfs systemctl -q enable multi-user.target
+        if [ ! -e $container_rootfs/etc/systemd/system/sigpwr.target ]; then
+            chroot $container_rootfs ln -s /usr/lib/systemd/system/halt.target /etc/systemd/system/sigpwr.target
+        fi
+
+        # systemd in userns won't be able to set /proc/self/oom_score_adj which
+        # prevents the dbus service from starting
+        sed -i 's|^OOMScoreAdjust|#LXC OOMScoreAdjust|' $container_rootfs/usr/lib/systemd/system/dbus.service
+        return
     fi
 
     # silence error in checking for selinux
@@ -255,6 +292,20 @@ EOF
     # don't try to unmount swap
     sed -i 's|\[ -f /proc/swaps \]|# LXC [ -f /proc/swaps ]|' $container_rootfs/etc/init.d/halt
 
+    # sem_open(3) checks that /dev/shm is SHMFS_SUPER_MAGIC, so make sure to
+    # mount /dev/shm (normally done by dracut initrd) as tmpfs
+    if [ $container_release_major = "4" -o $container_release_major = "5" ]; then
+        grep -q "mount -t tmpfs tmpfs /dev/shm" $container_rootfs/etc/rc.sysinit
+        if [ $? -eq 1 ]; then
+            echo "mount -t tmpfs tmpfs /dev/shm" >>$container_rootfs/etc/rc.sysinit
+            echo "mount -t tmpfs tmpfs /dev/shm" >>$container_rootfs/etc/rc.d/rc.sysinit
+        fi
+    fi
+    if [ $container_release_major = "6" ]; then
+        sed -i 's|mount -n -o remount /dev/shm >/dev/null 2>&1$|mount -t tmpfs tmpfs /dev/shm # LXC|' $container_rootfs/etc/rc.sysinit
+        sed -i 's|mount -n -o remount /dev/shm >/dev/null 2>&1$|mount -t tmpfs tmpfs /dev/shm # LXC|' $container_rootfs/etc/rc.d/rc.sysinit
+    fi
+
     # there might be other services that are useless but the below set is a good start
     # some of these might not exist in the image, so we silence chkconfig complaining
     # about the service file not being found
@@ -271,11 +322,6 @@ EOF
     do
         chroot $container_rootfs chkconfig 2>/dev/null $service on
     done
-
-    # ensure /dev/ptmx refers to the newinstance devpts of the container, or
-    # pty's will get crossed up with the hosts (https://lkml.org/lkml/2012/1/23/512)
-    rm -f $container_rootfs/dev/ptmx
-    ln -s pts/ptmx $container_rootfs/dev/ptmx
 }
 
 container_rootfs_configure()
@@ -311,17 +357,6 @@ EOF
 
     # this file has to exist for libvirt/Virtual machine monitor to boot the container
     touch $container_rootfs/etc/mtab
-
-    # sem_open(3) checks that /dev/shm is SHMFS_SUPER_MAGIC, so make sure to mount /dev/shm (normally done by dracut initrd) as tmpfs
-    if [ $container_release_major = "4" -o $container_release_major = "5" ]; then
-        echo "mount -t tmpfs tmpfs /dev/shm" >>$container_rootfs/etc/rc.sysinit
-        echo "mount -t tmpfs tmpfs /dev/shm" >>$container_rootfs/etc/rc.d/rc.sysinit
-    fi
-
-    if [ $container_release_major = "6" ]; then
-        sed -i 's|mount -n -o remount /dev/shm >/dev/null 2>&1$|mount -t tmpfs tmpfs /dev/shm # LXC|' $container_rootfs/etc/rc.sysinit
-        sed -i 's|mount -n -o remount /dev/shm >/dev/null 2>&1$|mount -t tmpfs tmpfs /dev/shm # LXC|' $container_rootfs/etc/rc.d/rc.sysinit
-    fi
 
     # setup console and tty[1-4] for login. note that /dev/console and
     # /dev/tty[1-4] will be symlinks to the ptys /dev/lxc/console and
@@ -389,7 +424,7 @@ EOF
     # /com/ubuntu/upstart socket.
     if [ $container_release_major = "4" -o $container_release_major = "5" ]; then
         sed -i 's|pf::powerfail:/sbin/shutdown -f -h +2 "Power Failure; |pf::powerfail:/sbin/shutdown -f -h now "|' $container_rootfs/etc/inittab
-    else
+    elif [ $container_release_major = "6" ]; then
         cat <<EOF > $container_rootfs/etc/init/power-status-changed.conf
 # power-status-changed - used to cleanly shut down the container
 #
@@ -440,6 +475,17 @@ EOF
         echo "lxc.cap.drop = sys_resource" >>$cfg_dir/config
     fi
 
+    # systemd services like logind and journald need these
+    if [ $container_release_major != "7" ]; then
+        echo "lxc.cap.drop = setfcap setpcap" >>$cfg_dir/config
+    fi
+
+    # don't create kmsg symlink as it causes journald to use 100% cpu
+    if [ $container_release_major = "7" ]; then
+        echo "lxc.autodev = 1" >>$cfg_dir/config
+        echo "lxc.kmsg = 0" >>$cfg_dir/config
+    fi
+
     echo "# Networking" >>$cfg_dir/config
     # see if the network settings were already specified
     lxc_network_type=`grep '^lxc.network.type' $cfg_dir/config | awk -F'[= \t]+' '{ print $2 }'`
@@ -469,6 +515,23 @@ container_rootfs_clone()
     else
         echo "Copying rootfs ..."
         cp -axT $template_rootfs $container_rootfs || die "copy template"
+    fi
+}
+
+container_rootfs_repo_create()
+{
+    echo "# LXC generated .repo file" >$1
+    echo "[$2]" >>$1
+    echo "name=Oracle Linux $container_release_major.$container_release_minor ($basearch)" >>$1
+    echo "baseurl=$3/" >>$1
+    echo "enabled=1" >>$1
+    echo "skip_if_unavailable=1" >>$1
+
+    if [ "$4" != "" ]; then
+        echo "gpgkey=$yum_url/RPM-GPG-KEY-oracle-ol$container_release_major" >>$1
+        echo "gpgcheck=1" >>$1
+    else
+        echo "gpgcheck=0" >>$1
     fi
 }
 
@@ -542,66 +605,83 @@ container_rootfs_create()
             die "The template is busy."
         fi
 
-        echo "Downloading release $container_release_major.$container_release_minor for $basearch"
+        echo "Yum installing release $container_release_major.$container_release_minor for $basearch"
 
-        # get yum repo file
         if [ -n "$repourl" ]; then
             yum_url=$repourl
         else
             yum_url=http://public-yum.oracle.com
         fi
-        if   [ $container_release_major = "4" ]; then
-            repofile=public-yum-el4.repo
-        elif [ $container_release_major = "5" ]; then
-            repofile=public-yum-el5.repo
-        elif [ $container_release_major = "6" ]; then
-            repofile=public-yum-ol6.repo
+        if [ $container_release_major = "4" -o $container_release_major = "5" ]; then
+            latest_L="el"
+            latest_U="EL"
         else
-            die "Unsupported release $container_release_major"
-        fi
-        mkdir -p $container_rootfs/etc/yum.repos.d
-        wget -q $yum_url/$repofile -O $container_rootfs/etc/yum.repos.d/$repofile
-        if [ $? -ne 0 ]; then
-            die "Failed to download repo file $yum_url/$repofile"
+            latest_L="ol"
+            latest_U="OL"
         fi
 
-        # yum will take $basearch from host, so force the arch we want
-        sed -i "s|\$basearch|$basearch|" $container_rootfs/etc/yum.repos.d/$repofile
-
-        # replace url if they specified one
-        if [ -n "$repourl" ]; then
-            sed -i "s|baseurl=http://public-yum.oracle.com/repo|baseurl=$repourl/repo|" $container_rootfs/etc/yum.repos.d/$repofile
-            sed -i "s|gpgkey=http://public-yum.oracle.com|gpgkey=$repourl|" $container_rootfs/etc/yum.repos.d/$repofile
-        fi
-
-        # disable all repos, then enable the repo for the version we are installing.
-        if [ $container_release_minor = "latest" ]; then
-            if [ $container_release_major = "4" -o $container_release_major = "5" ]; then
-                repo="el"$container_release_major"_"$container_release_minor
+        if [ -n "$baseurl" ]; then
+            # create .repo pointing at baseurl
+            repo="lxc-install"
+            mkdir -p $container_rootfs/etc/yum.repos.d
+            container_rootfs_repo_create \
+                $container_rootfs/etc/yum.repos.d/lxc-install.repo $repo $baseurl
+        else
+            # get public-yum repo file
+            if   [ $container_release_major = "4" ]; then
+                repofile=public-yum-el4.repo
+            elif [ $container_release_major = "5" ]; then
+                repofile=public-yum-el5.repo
+            elif [ $container_release_major = "6" ]; then
+                repofile=public-yum-ol6.repo
+            elif [ $container_release_major = "7" ]; then
+                repofile=public-yum-ol7.repo
             else
-                repo="ol"$container_release_major"_"$container_release_minor
+                die "Unsupported release $container_release_major"
             fi
-        elif [ $container_release_major = "6" ]; then
-            if   [ $container_release_minor = "0" ]; then
-                repo="ol"$container_release_major"_ga_base"
-            else
-                repo="ol"$container_release_major"_u"$container_release_minor"_base"
+
+            mkdir -p $container_rootfs/etc/yum.repos.d
+            wget -q $yum_url/$repofile -O $container_rootfs/etc/yum.repos.d/$repofile
+            if [ $? -ne 0 ]; then
+                die "Unable to download repo file $yum_url/$repofile, release unavailable"
             fi
-        elif [ $container_release_major = "5" ]; then
-            if   [ $container_release_minor = "0" ]; then
-                repo="el"$container_release_major"_ga_base"
-            elif [ $container_release_minor -lt "6" ]; then
+
+            # yum will take $basearch from host, so force the arch we want
+            sed -i "s|\$basearch|$basearch|" $container_rootfs/etc/yum.repos.d/$repofile
+
+            # replace url if they specified one
+            if [ -n "$repourl" ]; then
+                sed -i "s|baseurl=http://public-yum.oracle.com/repo|baseurl=$repourl/repo|" $container_rootfs/etc/yum.repos.d/$repofile
+                sed -i "s|gpgkey=http://public-yum.oracle.com|gpgkey=$repourl|" $container_rootfs/etc/yum.repos.d/$repofile
+            fi
+
+            # disable all repos, then enable the repo for the version we are installing.
+            if [ $container_release_minor = "latest" ]; then
+                repo=$latest_L""$container_release_major"_"$container_release_minor
+            elif [ $container_release_major = "7" ]; then
+                    repo="ol"$container_release_major"_u"$container_release_minor"_base"
+            elif [ $container_release_major = "6" ]; then
+                if   [ $container_release_minor = "0" ]; then
+                    repo="ol"$container_release_major"_ga_base"
+                else
+                    repo="ol"$container_release_major"_u"$container_release_minor"_base"
+                fi
+            elif [ $container_release_major = "5" ]; then
+                if   [ $container_release_minor = "0" ]; then
+                    repo="el"$container_release_major"_ga_base"
+                elif [ $container_release_minor -lt "6" ]; then
+                    repo="el"$container_release_major"_u"$container_release_minor"_base"
+                else
+                    repo="ol"$container_release_major"_u"$container_release_minor"_base"
+                fi
+            elif [ $container_release_major = "4" -a $container_release_minor -gt "5" ]; then
                 repo="el"$container_release_major"_u"$container_release_minor"_base"
             else
-                repo="ol"$container_release_major"_u"$container_release_minor"_base"
+                die "Unsupported release $container_release_major.$container_release_minor"
             fi
-        elif [ $container_release_major = "4" -a $container_release_minor -gt "5" ]; then
-            repo="el"$container_release_major"_u"$container_release_minor"_base"
-        else
-            die "Unsupported release $container_release_major.$container_release_minor"
+            sed -i "s|enabled=1|enabled=0|" $container_rootfs/etc/yum.repos.d/$repofile
+            sed -i "/\[$repo\]/,/\[/ s/enabled=0/enabled=1/" $container_rootfs/etc/yum.repos.d/$repofile
         fi
-        sed -i "s|enabled=1|enabled=0|" $container_rootfs/etc/yum.repos.d/$repofile
-        sed -i "/\[$repo\]/,/\[/ s/enabled=0/enabled=1/" $container_rootfs/etc/yum.repos.d/$repofile
 
         container_rootfs_dev_create
 
@@ -648,10 +728,19 @@ container_rootfs_create()
         fi
         if [ x"$redo_pkgs" != x ]; then
             rpm --root $container_rootfs --nodeps -e $redo_pkgs
-            yum $yum_args install $redo_pkgs
+            lxc-unshare -s MOUNT yum -- $yum_args install $redo_pkgs
             if [ $? -ne 0 ]; then
                 die "Unable to reinstall packages"
             fi
+        fi
+
+        # if installing from a baseurl, create a .repo that the container
+        # can use to update to _latest from http://public-yum.oracle.com
+        if [ -n "$baseurl" ]; then
+            container_rootfs_repo_create \
+                "$container_rootfs/etc/yum.repos.d/public-yum-"$latestL""$container_release_major".repo" \
+                $latest_L""$container_release_major"_latest" \
+                $yum_url"/repo/OracleLinux/"$latest_U""$container_release_major"/latest/$basearch" gpg
         fi
 
         # these distributions put the rpm database in a place the guest is
@@ -680,6 +769,9 @@ container_rootfs_create()
         chroot $container_rootfs rpm --rebuilddb >/dev/null 2>&1
 
     ) 9>@LOCALSTATEDIR@/lock/subsys/lxc-oracle-$name
+    if [ $? -ne 0 ]; then
+        exit 1
+    fi
 }
 
 container_release_get()
@@ -709,23 +801,25 @@ usage()
   -R|--release=<release>  release to download for the new container
   --rootfs=<path>         rootfs path
   -r|--rpms=<rpm name>    additional rpms to install into container
-  -u|--url=<url>          replace yum repo url (ie. local yum mirror)
+  -u|--url=<url>          replace yum repo url (ie. Oracle public-yum mirror)
+     --baseurl=<url>      use package repository (ie. file:///mnt)
+                          arch and release must also be specified
   -t|--templatefs=<path>  copy/clone rootfs at path instead of downloading
   -P|--patch=<path>       only patch the rootfs at path for use as a container
   -h|--help
 
 Release is of the format "major.minor", for example "5.8", "6.3", or "6.latest"
+This template supports Oracle Linux releases 4.6 - 7.0
 EOF
     return 0
 }
 
-options=$(getopt -o hp:n:a:R:r:u:t: -l help,rootfs:,path:,name:,arch:,release:,rpms:,url:,templatefs:,patch: -- "$@")
+options=$(getopt -o hp:n:a:R:r:u:t: -l help,rootfs:,path:,name:,arch:,release:,rpms:,url:,templatefs:,patch:,baseurl: -- "$@")
 if [ $? -ne 0 ]; then
     usage $(basename $0)
     exit 1
 fi
 
-arch=$(uname -m)
 eval set -- "$options"
 while true
 do
@@ -740,6 +834,7 @@ do
         -u|--url)		repourl=$2; shift 2;;
         -t|--templatefs)	template_rootfs=$2; shift 2;;
         --patch)		patch_rootfs=$2; shift 2;;
+        --baseurl)		baseurl=$2; shift 2;;
         --)             	shift 1; break ;;
         *)              	break ;;
     esac
@@ -749,6 +844,18 @@ done
 if [ "$(id -u)" != "0" ]; then
     echo "This script should be run as 'root'"
     exit 1
+fi
+
+if [ -n "$baseurl" ]; then
+    if [ "$arch" = "" -o "$container_release_version" = "" ]; then
+        echo "The --arch and --release must be specified when using --baseurl"
+        usage
+        exit 1
+    fi
+fi
+
+if [ "$arch" = "" ]; then
+    arch=$(uname -m)
 fi
 
 if [ -n "$patch_rootfs" ]; then
